import logging
from pathlib import Path
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import inch

logger = logging.getLogger(__name__)

def save_to_pdf(records, output_path=None):
    if not records:
        logger.warning("No records to save to PDF")
        return False
    if output_path is None:
        output_path = Path("output") / "universities.pdf"
    else:
        output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=landscape(A4),
            leftMargin=20, rightMargin=20, topMargin=20, bottomMargin=20,
            title="University Faculty Data",
            author="noahotim/university-faculty-data-scraper"
        )
        styles = getSampleStyleSheet()
        title = Paragraph(f"<b>University Faculty Data</b> — {len(records)} records from {len({r['University'] for r in records})} universities", styles['Title'])
        subtitle = Paragraph("Generated by noahotim/university-faculty-data-scraper | https://github.com/noahotim/university-faculty-data-scraper", styles['Normal'])
        # Build table
        headers = ["University", "Faculty", "Department", "Name", "Position"]
        data = [headers]
        for r in records:
            row = [r.get(h, "")[:40] for h in headers]
            # wrap long text
            row = [Paragraph(str(c), styles['Normal']) if len(str(c)) > 25 else str(c) for c in row]
            data.append(row)
        col_widths = [130, 130, 110, 110, 110]
        table = Table(data, colWidths=col_widths, repeatRows=1)
        style = TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0a66c2")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 8),
            ('FONTSIZE', (0,1), (-1,-1), 7),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f5f7fb")]),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ])
        table.setStyle(style)
        story = [title, Spacer(1, 6), subtitle, Spacer(1, 12), table]
        doc.build(story)
        logger.info(f"Successfully saved {len(records)} records to PDF: {output_path}")
        return True
    except Exception as e:
        logger.error(f"Failed to save PDF: {e}", exc_info=True)
        return False

if __name__ == "__main__":
    import csv
    p = Path("output/universities.csv")
    if p.exists():
        with p.open(encoding="utf-8") as f:
            recs = list(csv.DictReader(f))
        print(save_to_pdf(recs))
    else:
        print("no csv")
